[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mradnet"
version = "0.1.0"
description = "Radar Object Detection with mRadNet"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cruw-devkit",
    "line-profiler>=4.0.0",
    "numpy",
    "pyqt6",
    "pyyaml",
    "tensorboard",
    "timm",
    "torch",
    "torchvision",
    "tqdm",
]

[tool.uv.sources]
cruw-devkit = { git = "https://github.com/yizhou-wang/cruw-devkit.git" }

[tool.setuptools]
# This tells setuptools to treat these folders as top-level packages.
# Use 'import model', 'import dataset', 'import utils'
packages = ["model", "dataset", "utils"]