---
name: mRadNet
seed: 0
exp_dir: # Your path to save checkpoints and logs
eval_tmp_dir: # Your path to save temporary evaluation files

dataset:
  root_path: # Your path to CRUW dataset
  confamaps_save_path: # Your path to save precomputed confmaps
  chirps: [0, 64, 128, 192]
  class_names: [pedestrian, cyclist, car]
  class_sizes:
    pedestrian: 12 # 0.5 meters
    cyclist: 18 # 1.0 meters
    car: 24 # 3.0 meters
  confmap:
    conf_threshold: 0.01
    lnms_threshold: 0.5
  helper_sensor_config: sensor_config_rod2021
  helper_object_config: object_config
  input_size: [128, 128]
  input_range: [1.0, 25.0, -1.0472, 1.0472] # [r_min, r_max, a_min, a_max]
  test_list: # https://github.com/Zhuanglong2/T-RODNet#prepare-data-for-t-rodnet
    - 2019_04_09_BMS1001
    - 2019_04_30_MLMS001
    - 2019_05_23_PM1S013
    - 2019_09_29_ONRD005

model:
  encoder:
    patch_size: [2, 2, 2] # [T, R, A]
    depths: [2, 2, 2, 1]
    dims: [48, 96, 192, 384]
  decoder:
    depths: [2, 2, 2]
    embed_dim: 64
    out_channels: 64
  output_size: [128, 128]
  window_size: 16 # length of sliding temporal window
  window_step: 4 # skip size of sliding temporal window

train:
  num_epochs: 20
  batch_size: 4
  learning_rate: 1.0e-4
  weight_decay: 0
